apiVersion: v1
kind: Service
metadata:
  name: fluent-bit-syslog
  namespace: vcr-fluent-syslog
spec:
  type: NodePort
  ports:
  - port: 5140
    targetPort: 5140
    nodePort: 30140
  selector:
    app: fluent-bit

